### PR TITLE
feat : Set Test Env

### PR DESCRIPTION
**Pull request by gimseonjin**

### CODE REVIEW

**Comment by gimseonjin** [comment]
|File|Coverage [100%]|:green_apple:|
|:-|:-:|:-:|
|[HealthController.java](https://github.com/f-lab-edu/todo-list/blob/7368dc3f608ad1ea04d984b685eb3855fbd1c63f/src%2Fmain%2Fjava%2Fcom%2Fflab%2Ftodo%2Fhealth%2FHealthController.java)|100%|:green_apple:|

|Total Project Coverage|100%|:green_apple:|
|:-|:-:|:-:|

**Comment by gimseonjin** [comment]
|File|Coverage [100%]|:green_apple:|
|:-|:-:|:-:|
|[HealthController.java](https://github.com/f-lab-edu/todo-list/blob/3c15eb9fa6f59600d5bb6f4f3c52c1de8e6a7cab/src%2Fmain%2Fjava%2Fcom%2Fflab%2Ftodo%2Fhealth%2FHealthController.java)|100%|:green_apple:|

|Total Project Coverage|100%|:green_apple:|
|:-|:-:|:-:|

**Comment by gimseonjin** [comment]
|File|Coverage [100%]|:green_apple:|
|:-|:-:|:-:|
|[HealthController.java](https://github.com/f-lab-edu/todo-list/blob/f32dceb70b20ff26e8527c1d48ff58aacf30a3e4/src%2Fmain%2Fjava%2Fcom%2Fflab%2Ftodo%2Fhealth%2FHealthController.java)|100%|:green_apple:|

|Total Project Coverage|100%|:green_apple:|
|:-|:-:|:-:|

**Review by jaeyeonme — APPROVED** [review]
LGTM

**Pull request merged**
